version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    container_name: dj_tmp_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./app:/app/
      - ./app/static:/app/static/
    expose:
      - 8001
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    container_name: dj_tmp_db
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pwd

  nginx:
    build: ./nginx
    container_name: dj_tmp_nginx
    volumes:
      - ./app/static:/app/static/
    ports:
      - 8001:80
    depends_on:
      - web